name: Oracle Cloud Auto Create

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */3 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Run Macro Script
        env:
          OCI_USER: ${{ secrets.OCI_USER }}
          OCI_TENANCY: ${{ secrets.OCI_TENANCY }}
          OCI_FINGERPRINT: ${{ secrets.OCI_FINGERPRINT }}
          OCI_REGION: ${{ secrets.OCI_REGION }}
          OCI_KEY_CONTENT: ${{ secrets.OCI_KEY_CONTENT }}
          OCI_COMPARTMENT_ID: ${{ secrets.OCI_COMPARTMENT_ID }}
          OCI_SSH_PUBLIC_KEY: ${{ secrets.OCI_SSH_PUBLIC_KEY }}
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          chmod +x ./script/oci-create.sh
          ./script/oci-create.sh
